export const SELLER_LOGIN_REQUEST = "SELLER_LOGIN_REQUEST";
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS";
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL";

export const SELLER_SIGNUP_REQUEST = "SELLER_SIGNUP_REQUEST";
export const SELLER_SIGNUP_SUCCESS = "SELLER_SIGNUP_SUCCESS";
export const SELLER_SIGNUP_FAIL = "SELLER_SIGNUP_FAIL";

export const SELLER_LOGOUT_REQUEST = "SELLER_LOGOUT_REQUEST";
export const SELLER_LOGOUT_SUCCESS = "SELLER_LOGOUT_SUCCESS";
export const SELLER_LOGOUT_FAIL = "SELLER_LOGOUT_FAIL";
